name: gas_cylinder
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  get: ^4.6.6
  dio: ^5.4.0
  logger: ^2.0.2+1
  pinput: ^4.0.0
  flutter_svg: ^2.0.9
  flutter_screenutil: ^5.9.0
  flutter_native_splash: ^2.3.10
  cached_network_image: ^3.3.1
  image_cropper: ^5.0.1
  image_picker: ^1.0.7
  flutter_spinkit: ^5.2.0
  font_awesome_flutter: ^10.7.0
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  animate_do: ^3.3.3
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1
  connectivity_plus: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

# launcher icons
flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/logos/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logos/app_icon.png"

# Native splash
flutter_native_splash:
  android: true
  ios: true
  web: false
  # color: "#0089FF"
  background_image: "assets/images/splash/splash_bg.png"
  image: assets/images/splash/splash_logo.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/splash/
    - assets/images/welcome/
    - assets/images/auth/
    - assets/icons/
    - assets/icons/settings/
    - assets/icons/auth/
    - assets/icons/bottom_nav/
    - assets/icons/drawer/
    - assets/demo_user/
    - assets/icons/entryPoint/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
